const countryExtension = ({ country }) => {
  const extension = [
    { code: "af", country: "Afghanistan" },
    { code: "al", country: "Albania" },
    { code: "dz", country: "Algeria" },
    { code: "ao", country: "Angola" },
    { code: "ar", country: "Argentina" },
    { code: "au", country: "Australia" },
    { code: "at", country: "Austria" },
    { code: "bd", country: "Bangladesh" },
    { code: "be", country: "Belgium" },
    { code: "br", country: "Brazil" },
    { code: "ca", country: "Canada" },
    { code: "cn", country: "China" },
    { code: "co", country: "Colombia" },
    { code: "cz", country: "Czech Republic" },
    { code: "dk", country: "Denmark" },
    { code: "eg", country: "Egypt" },
    { code: "fr", country: "France" },
    { code: "de", country: "Germany" },
    { code: "gh", country: "Ghana" },
    { code: "gr", country: "Greece" },
    { code: "in", country: "India" },
    { code: "id", country: "Indonesia" },
    { code: "ir", country: "Iran" },
    { code: "iq", country: "Iraq" },
    { code: "ie", country: "Ireland" },
    { code: "il", country: "Israel" },
    { code: "it", country: "Italy" },
    { code: "jp", country: "Japan" },
    { code: "ke", country: "Kenya" },
    { code: "kr", country: "South Korea" },
    { code: "mx", country: "Mexico" },
    { code: "ma", country: "Morocco" },
    { code: "nl", country: "Netherlands" },
    { code: "ng", country: "Nigeria" },
    { code: "no", country: "Norway" },
    { code: "pk", country: "Pakistan" },
    { code: "pl", country: "Poland" },
    { code: "pt", country: "Portugal" },
    { code: "ru", country: "Russia" },
    { code: "sa", country: "Saudi Arabia" },
    { code: "za", country: "South Africa" },
    { code: "es", country: "Spain" },
    { code: "se", country: "Sweden" },
    { code: "ch", country: "Switzerland" },
    { code: "tr", country: "Turkey" },
    { code: "ua", country: "Ukraine" },
    { code: "gb", country: "United Kingdom" },
    { code: "us", country: "United States" },
    { code: "vn", country: "Vietnam" },
  ];

  const match = extension.find((item) => item.country === country);
  return match ? match.code : "not found";
};

export default countryExtension;
